---
title: DCM Assessment Report
subtitle: STAT 134 Su26 - Quiz 5
jupyter:
  kernelspec:
    display_name: .venv (3.14.7)
    language: python
    name: python3
execute:
  warning: false
  message: false
  eval: true
  echo: false
format:
  typst:
    toc-title: Contents
    toc: true
    toc-depth: 2
    number-sections: true
    number-depth: 3
---


```{python}
#| label: Parameters
#| tags: [parameters]

threshold = .8
model_type = 'DINA'

attr1 = 'expect_weight_avg'
attr2 = 'expect_fun'
attr3 = 'def_var'
attr4 = 'prop_expect'
attr5 = 'expect_famous_dist'
attr6 = 'cond_expect'
attr7 = 'prop_var'
```

```{python}
import sys
print(sys.executable)
```

```{python}
#| output: false
#| label: Packages

import pandas as pd
import numpy as np
import matplotlib
import plotnine as pn
from janitor import clean_names
from great_tables import GT as gt
import matplotlib.pyplot as plt
from pyhere import here
from pathlib import Path
import tempfile
from cmdstanpy import CmdStanModel
import joblib
import os

pd.set_option('display.max_columns', None)
matplotlib.rcParams.update({'savefig.bbox': 'tight'})
pn.theme_set(pn.theme_classic())

data_directory = 'data/'
q_directory = 'q_matrix/'
stan_directory = 'stan_models/no_testlet/non_informative_priors/'
diagnose_directory = 'reports/diagnostics/'

os.makedirs(here(diagnose_directory), exist_ok=True)
os.makedirs(here('reports/2026/quiz2/'), exist_ok=True)
```

# Creating Necessary DataFrames & Matrices

```{python}
#| label: DataFrame & Q-Matrix

df = pd.read_csv(here(f'{data_directory}stat_134_2025_quiz5.csv')).drop(columns = 'Unnamed: 0')
q = pd.read_csv(here(f'{q_directory}quiz5_q_updated.csv')).clean_names(case_type = 'snake').drop(columns = 'unnamed_0')
q['item'] = ['item' + str(i) for i in q['item']]

# if no testlet, run this code
q = q.drop(columns = 'question')

print(df.head())
print(q.head())
```


```{python}
# removing final question because all scored 1 (typo in quiz)
df = df.drop(columns = 'item35')
df.head()
```

```{python}
# dropping the final skill because only used once and no variation
q = q.drop(columns = 'total_variance')
q = q.loc[q['item'] != 'item35']
q.head()
```

# Attribute Profile Matrix

```{python}
#| label: Attribute profile matrix

alpha = pd.DataFrame([(a, b, c, d, e, f, g) for a in np.arange(2) for b in np.arange(2) for c in np.arange(2) for d in np.arange(2) for e in np.arange(2) for f in np.arange(2) for g in np.arange(2)])
      
alpha = alpha.rename(columns = {0: 'attr1',
                                1: 'attr2',
                                2: 'attr3',
                                3: 'attr4',
                                4: 'attr5',
                                5: 'attr6',
                                6: 'attr7'})

alpha['class_label'] = alpha.astype(int).astype(str).agg(''.join, axis = 1)
alpha = alpha.reset_index()
alpha['index'] = alpha['index'] + 1

alpha.head()
```

# Global Attribute Mastery Indicator Matrix

### BUG here

```{python}
#| label: Global attribute mastery

xi = np.zeros((q.shape[0], alpha.shape[0]), dtype = int)

if model_type == 'DINO':
  # DINO model
  for i in range(q.drop(columns = 'item').shape[0]):
    for c in range(alpha.drop(columns = ['index', 'class_label']).shape[0]):
      dino_eta[i,c] = 1 - np.prod((1 - alpha.drop(columns = ['index', 'class_label']).to_numpy()[c, :]) ** q.drop(columns = 'item').to_numpy()[i, :])

elif model_type == 'DINA':
  # DINA model
  for i in range(q.drop(columns = 'item').shape[0]):
    for c in range(alpha.drop(columns = ['index', 'class_label']).shape[0]):
      xi[i,c] = np.prod(alpha.drop(columns = ['index', 'class_label']).to_numpy()[c, :] ** q.drop(columns = 'item').to_numpy()[i, :])
```

```{python}
#| label: Stan dictionary

stan_dict = {
  'J': df.drop(columns = 'anon_id').shape[0],
  'I': df.drop(columns = 'anon_id').shape[1],
  'C': alpha.drop(columns = ['class_label', 'index']).shape[0],
  'K': q.drop(columns = 'item').shape[1],
  'Y': df.drop(columns = 'anon_id').to_numpy(),
  'Q': q.drop(columns = 'item').to_numpy(),
  'alpha': alpha.drop(columns = ['class_label', 'index']).to_numpy(),
  'xi': xi
}
```

# Stan Code  

```{python}
#| label: model execution
#| output: false

file = os.path.join(here(f'{stan_directory}dino_dina_model.stan'))
model = CmdStanModel(stan_file = file,
                     compile = 'force',
                     cpp_options = {'STAN_THREADS': 'TRUE'})

np.random.seed(7102026)
  
# MLE Estimation
fit = model.optimize(
    data=stan_dict,
    algorithm='lbfgs',
    iter=2000,
    show_console=True
)
                   
joblib.dump([model, fit],
            here(f'{stan_directory}testlet_dino_dina_mle.joblib'),
            compress = 3)
```

```{python}
#| label: Stan MLE parameter extraction
#| output: false

# Extract the single point estimates from the MLE fit
fitdf = fit.optimized_params_pd
```

```{python}
#| label: All code run for plots/tables

# Slipping & guessing
sg = fitdf.filter(regex = 'guess|slip').reset_index(drop=True)
sglong = sg.melt()
sglong['variable'] = sglong['variable'].str.replace(']', '', regex=False)
sglong[['type', 'item']] = sglong['variable'].str.split('[', expand = True)
sglong['item'] = sglong['item'].astype(int)

sgavg = sglong[['item', 'type', 'value']].rename(columns={'value': 'estimate'})

# pi matrix (classes getting items correct)
pidf = fitdf.filter(regex = 'pi').reset_index(drop=True)
pilong = pidf.melt()
pilong['variable'] = pilong['variable'].str.replace('pi[', '', regex=False)
pilong['variable'] = pilong['variable'].str.replace(']', '', regex=False)
pilong[['item', 'latclass']] = pilong['variable'].str.split(',', expand = True)
pilong[['item', 'latclass']] = pilong[['item', 'latclass']].astype(int)

piavg = pilong[['item', 'latclass', 'value']].rename(columns={'value': 'estimate'})
piavg = piavg.merge(alpha, how='left', left_on='latclass', right_on='index')

# attribute calculations
attrdf = fitdf.filter(regex = '^prob_resp_attr').reset_index(drop=True)
attrlong = attrdf.melt()
attrlong['variable'] = attrlong['variable'].str.replace('prob_resp_attr[', '', regex=False)
attrlong['variable'] = attrlong['variable'].str.replace(']', '', regex=False)
attrlong[['stu', 'attr']] = attrlong['variable'].str.split(',', expand = True)
attrlong[['stu', 'attr']] = attrlong[['stu', 'attr']].astype(int)

attravg = attrlong[['stu', 'attr', 'value']].rename(columns={'value': 'estimate'})

# mastery/proficiency thresholds
attravg['mastery'] = np.where(attravg['estimate'] > threshold, 1, 0)
attr_w = attravg.pivot(index = 'stu', columns = 'attr', values = 'mastery').reset_index()

# reliability
attravg['acc_comp'] = attravg['estimate'].apply(lambda p: max(p, 1 - p))
attravg['cons_comp'] = attravg['estimate'].apply(lambda p: p**2 + (1 - p)**2)

# latent classes
attr_class = fitdf.filter(regex = '^prob_resp_class').reset_index(drop=True)
class_long = attr_class.melt()
class_long['variable'] = class_long['variable'].str.replace('prob_resp_class[', '', regex=False)
class_long['variable'] = class_long['variable'].str.replace(']', '', regex=False)
class_long[['stu', 'latclass']] = class_long['variable'].str.split(',', expand = True)
class_long[['stu', 'latclass']] = class_long[['stu', 'latclass']].astype(int)
class_long = class_long.rename(columns={'value': 'estimate'})

class_max = class_long.loc[class_long['estimate'] == class_long.groupby('stu')['estimate'].transform('max')].copy()
class_max = class_max.rename(columns={'latclass': 'class_member'})

class_avg = class_max.merge(alpha, how='inner', left_on='class_member', right_on='index')

# Class proportions based on average predicted probabilities
class_prop = class_long.groupby('latclass')['estimate'].mean().reset_index()
class_prop = class_prop.merge(alpha, how='inner', left_on='latclass', right_on='index')
```

# Latent Classes
Latent classes map respondents into groups based on what skill(s) they are proficient in. The proportions indicate the estimated likelihood of a respondent belonging to each profile class given their item responses.

```{python}
#| label: Latent classes - respondent class membership < .5

(
  pn.ggplot(class_avg.loc[class_avg['estimate'] < .5],
    pn.aes('stu', 'estimate'))
  + pn.geom_point(pn.aes(color = 'factor(class_label)'),
                  alpha = .7)
  + pn.coord_flip()
  + pn.scale_color_brewer('qual', 'Dark2')
  + pn.labs(title = 'Point Estimate of Membership in Latent Classes',
            subtitle = 'For Each Respondent (Estimate < 0.5)')
)
```

```{python}
#| label: Latent classes - respondent class membership .5 - .75

(
  pn.ggplot(class_avg.loc[class_avg['estimate'].between(.5, .75)],
    pn.aes('stu', 'estimate'))
  + pn.geom_point(pn.aes(color = 'factor(class_label)'),
                  alpha = .7)
  + pn.coord_flip()
  + pn.scale_color_brewer('qual', 'Dark2')
  + pn.labs(title = 'Point Estimate of Membership in Latent Classes',
            subtitle = 'For Each Respondent (Estimate 0.5 - 0.75)')
)
```

```{python}
#| label: Latent classes - respondent class membership .75 - .95

(
  pn.ggplot(class_avg.loc[(class_avg['estimate'] <= .95) & (class_avg['estimate'] >= .75)],
    pn.aes('stu', 'estimate'))
  + pn.geom_point(pn.aes(color = 'factor(class_label)'),
                  alpha = .7)
  + pn.coord_flip()
  + pn.scale_color_brewer('qual', 'Dark2')
  + pn.labs(title = 'Point Estimate of Membership in Latent Classes',
            subtitle = 'For Each Respondent (Estimate 0.75 - 0.95)')
)
```

```{python}
#| label: Latent classes - Respondent class membership > .95

(
  pn.ggplot(class_avg.loc[class_avg['estimate'] > .95],
    pn.aes('stu', 'estimate'))
  + pn.geom_point(pn.aes(color = 'factor(class_label)'),
                  alpha = .7)
  + pn.coord_flip()
  + pn.scale_color_brewer('qual', 'Dark2')
  + pn.labs(title = 'Point Estimate of Membership in Latent Classes',
            subtitle = 'For Each Respondent (Estimate > 0.95)')
)
```

We can also get the proportions of respondents that are in each class. This can indicate where the majority of students are at in regard to being proficient in the skills assessed in your quiz/assessment.

```{python}
#| label: Latent classes - Proportions in each class

(
  pn.ggplot(class_prop,
            pn.aes('factor(class_label)',
                   'estimate'))
  + pn.geom_point(alpha = .7,
                  color = 'seagreen')
  + pn.coord_flip()
  + pn.labs(title = 'Point Estimate of Latent Class Proportions')
)
```

# Proficiency/Mastery
While calculations are created to see how many respondents can be deemed proficent in each of the skills (see report folder), we can also see generally how many respondents are above the designated threshold. Being above the threshold indicates that on average, these respondents are likely to be proficient for that skill.

```{python}
#| label: Plot - respondent proficiency

(
  pn.ggplot(attravg,
            pn.aes('stu',
                   'estimate'))
  + pn.geom_point(alpha = .7,
                  color = 'seagreen')
  + pn.geom_hline(yintercept = threshold,
                  color = 'black',
                  linetype = 'dashed')
  + pn.facet_wrap('attr')
  + pn.theme(legend_position = 'none',
             axis_text_x = pn.element_blank())
)
```

```{python}
#| label: Proficiency List

attr_w = pd.concat([df['anon_id'], attr_w.drop(columns='stu')], axis = 1)

# Dynamically mapping attribute columns to their names up to the available number of attributes
attr_cols = [attr1, attr2, attr3, attr4, attr5, attr6, attr7]
col_mapping = {i+1: attr_cols[i] for i in range(len(attr_w.columns) - 1)}
attr_w = attr_w.rename(columns=col_mapping)

gt(attr_w.drop(columns = 'anon_id'))
```

```{python}
#| label: Proficiency data (csv)

attravg.drop(columns = ['acc_comp', 'cons_comp']).to_csv(here('reports/2026/quiz2/respondent_proficiency_raw.csv'))
attr_w.to_csv(here('reports/2026/quiz2/respondent_proficiency_list.csv'))
```

# Item-Level Slipping & Guessing

Slipping and guessing parameters focus on the probability that a respondent will slip or guess for each item. Slipping is the probability that a respondent will get an item incorrect even though they have at least one skill that measures that item (DINO) or all the skills assessed through that item (DINA). Guessing is the probability that a respondent will get an item correct even though they may not have at least one skill that measures the item (DINO) or all the skills needed for that item (DINA).

```{python}
#| label: Plot - slipping and guessing

(
  pn.ggplot(sgavg,
    pn.aes('factor(item)', 'estimate'))
  + pn.geom_point(pn.aes(color = 'type'),
                  alpha = .7)
  + pn.coord_flip()
  + pn.facet_wrap('type')
  + pn.scale_y_continuous(limits = [0, 1],
                          breaks = np.arange(0, 1.1, .1))
  + pn.scale_color_brewer('qual', 'Dark2')
  + pn.labs(title = 'Point Estimate of Guessing/Slipping',
            x = 'Item',
            y = 'Estimate',
            caption = 'Guess = Guessed and got answer correct\nSlip = Should know the answer, but got the item wrong')  
  + pn.theme(legend_position = 'none')
)
```

# Probabilities of Each Class Getting Items Correct
Depending on whatever class respondents belong to, these plots show which items a respondent in each class is likely to get correct. For the class that should have all the skills, a respondent should have all or most of the items correct. Similarly, the class lacking proficiency in the skills should show a respondent is likely to get most of the items incorrect.

```{python}
#| label: Pi matrix - Items likelihood of items correct by class

(
  pn.ggplot(piavg,
            pn.aes('item',
                   'estimate'))
  + pn.geom_point(alpha = .7,
                  color = 'seagreen')
  + pn.geom_hline(yintercept = .5,
  color = 'black',
  linetype = 'dashed')
  + pn.scale_x_continuous(limits = [1, piavg['item'].unique().max()],
                          breaks = piavg['item'].unique())
  + pn.coord_flip()
  + pn.facet_wrap('class_label')
  + pn.labs(title = 'Point Estimate of Getting Items Correct',
  subtitle = 'By Latent Class')
  + pn.theme(legend_position = 'none')
)
```

```{python}
#| label: Pi matrix for class with all proficiencies

(
  pn.ggplot(piavg.loc[piavg['class_label'] == '1111111'],
            pn.aes('item',
                   'estimate'))
  + pn.geom_point(alpha = .7,
                  color = 'seagreen')
  + pn.geom_hline(yintercept = .5,
  color = 'black',
  linetype = 'dashed')
  + pn.scale_x_continuous(limits = [1, piavg['item'].unique().max()],
                          breaks = piavg['item'].unique())
  + pn.coord_flip()
  + pn.facet_wrap('class_label')
  + pn.labs(title = 'Point Estimate of Getting Items Correct',
  subtitle = 'By Latent Class')
  + pn.theme(legend_position = 'none')
)
```

#Reliability
Model reliability can be broken down into two parts. First, accuracy of the DCM is how well the model is measuring true proficiency of the skills. Second, consistency is a measure of how likely a respondent would get the same proficiency values if tested again.

```{python}
#| label: Reliability metrics for model

reliability = attravg.groupby('attr').agg(
    accuracy = ('acc_comp', 'mean'),
    consistency = ('cons_comp', 'mean')
).reset_index()

gt(reliability.round(3)).tab_header(title = 'Accuracy & Consistency')
```

